name: matrix-webhook
description: Home Assistant add-on for matrix-webhook using vampywiz17/matrix-webhook image.
url: https://github.com/vampywiz17/matrix-webhook
image: vampywiz17/matrix-webhook
arch: [ amd64, armv7 ]
ingress: true
ingress_port: 8000
panel_icon: "mdi:chat"

version: 0.0.1
slug: matrix-webhook
startup: services
boot: auto
ports:
  8000/tcp: 8006
ports_description:
  8000/tcp: Webhook
options: {}
schema: {}
