name: matrix-webhook
description: Home Assistant add-on for matrix-webhook using vampywiz17/matrix-webhook image.
url: https://github.com/vampywiz17/matrix-webhook
image: vampywiz17/matrix-webhook
arch: [ amd64, armv7 ]
ingress: true
ingress_port: 8000
panel_icon: "mdi:chat"

version: 0.0.1
slug: matrix-webhook
startup: services
boot: auto
ports:
  8000/tcp: 8006
ports_description:
  8000/tcp: Webhook
options:
  MESSAGE_FORMAT: yaml
  USE_MARKDOWN: false
  ALLOW_UNICODE: true
  DISPLAY_APP_NAME: true
  MATRIX_SERVER: "https://matrix.example.org"
  MATRIX_SSLVERIFY: true
  MATRIX_USERID: "@myhook:matrix.example.org"
  MATRIX_PASSWORD: "mypass+*!word"
  MATRIX_DEVICE: "any-device-name-eg-docker"
  MATRIX_ADMIN_ROOM: "!privatechatwiththebotuser:matrix.example.org"
  KNOWN_TOKENS: "YOURSECRETTOKEN,!myroomid:matrix.example.org,Curl anOTheRToKen99,!myroomid2:matrix.example.org,Grafana"

schema:
  MESSAGE_FORMAT:
    type: select
    name: Message Format
    options:
      - yaml
      - json
      - raw
    default: raw
  USE_MARKDOWN:
    type: bool
    name: Use Markdown
  ALLOW_UNICODE:
    type: bool
    name: Allow Unicode
  DISPLAY_APP_NAME:
    type: bool
    name: Display App Name
  MATRIX_SERVER:
    type: str
    name: Matrix Server URL
  MATRIX_SSLVERIFY:
    type: bool
    name: Verify SSL
  MATRIX_USERID:
    type: str
    name: Matrix User ID
  MATRIX_PASSWORD:
    type: str
    name: Matrix Password
  MATRIX_DEVICE:
    type: str
    name: Device Name
  MATRIX_ADMIN_ROOM:
    type: str
    name: Admin Room ID
  KNOWN_TOKENS:
    type: str
    name: Known Tokens
environment:
  MESSAGE_FORMAT: "{{ MESSAGE_FORMAT }}"
  USE_MARKDOWN: "{{ USE_MARKDOWN }}"
  ALLOW_UNICODE: "{{ ALLOW_UNICODE }}"
  DISPLAY_APP_NAME: "{{ DISPLAY_APP_NAME }}"
  MATRIX_SERVER: "{{ MATRIX_SERVER }}"
  MATRIX_SSLVERIFY: "{{ MATRIX_SSLVERIFY }}"
  MATRIX_USERID: "{{ MATRIX_USERID }}"
  MATRIX_PASSWORD: "{{ MATRIX_PASSWORD }}"
  MATRIX_DEVICE: "{{ MATRIX_DEVICE }}"
  MATRIX_ADMIN_ROOM: "{{ MATRIX_ADMIN_ROOM }}"
  KNOWN_TOKENS: "{{ KNOWN_TOKENS }}"

map:
  - config:rw
